### ISSUE TITLE
Great work!  One idea to mention.

### ISSUE THREAD

**Issue by arcsoundguy** [ErikAlfredsson/sonos-sync-group-volume#1]
What a fantastic job Erik!  Well done!  I'm not very experienced with GitHub, sorry if this is a bad way to leave feedback.

When I was first developing this I found that when the group first wakes e.g. in the morning, the volume of the group was very slow to sync.

It turned out there was a web hook storm and all requests were being processed at the same time causing latency.

I ended up serializing the requests with a lockfile.  Another idea might be to filter the web hook events since during the storm possibly many events are unrelated to volume.  Your code may handle this already, but in case that wasn't obvious I wanted to mention it.

Great work again!  Very cool!  I will reference this repo from my repo as well very soon.

**Comment by ErikAlfredsson** [comment]
Thanks @arcsoundguy! And thanks to you for the original idea :)

I don't think I've noticed the slowdown you're talking about but maybe I've just missed it... I did notice that when I first start the Jishi Sonos API there's a load of web hooks coming through, kind of feels like it's sending all of them maybe to broadcast the initial state or something but I'm not sure. I kind of solved that by ignoring all web hooks the first 3 seconds from startup. But after that initial storm I haven't experienced anymore slowdowns (I haven't had the time to try it for that long yet though). 

I am filtering the web hooks already so it doesn't do anything unless the event is `"volume-change"` or `"mute-change"`. Feels really fast most of the time, almost instat!

If you want to try my implementation but something isn't working please let me know and I'll try to help!

**Comment by arcsoundguy** [comment]
I suspect the event filtering and startup web hook ignoring is probably a great solution.  You would certainly notice the problem after a few days use if it was present.  It sounds like your code handles this already.  I've linked to this project from my project as well.

**Comment by ErikAlfredsson** [comment]
Thank you! ✨
