### ISSUE TITLE
Nodejs 18 

### ISSUE THREAD

**Issue by quiggy** [ErikAlfredsson/sonos-sync-group-volume#3]
If I try to use your application with nodejs 18 i get an connection refused error when a webhook is recieved. This is caused by a different behaviour in nodejs 18 and node-fetch. Please have a look at this link:

https://github.com/node-fetch/node-fetch/issues/1624

Unfortunately with the default config of node-sonos-http-api its only listening to ipv4 requests. 
Because of the node-fetch behaviour and your application is using http://localhost:5005 as BASE_URL in utils.js it tries to reach the api on http://[::1]:5005 and gets an connectiion refused. 

If you change the BASE_URL to http://127.0.0.1:5005 it also works properly with nodejs18 because it will call the ipv4 instead of ipv6!

I think there is no downside in changing that, right?

Thanks!
Quiggy

**Comment by ErikAlfredsson** [comment]
I wasn't aware of this issue but there shouldn't be any downside to making that change no! If it works for you I'll try to update the code in this repository as well so any future users don't run into the same issue!

Thanks for finding a solution to the problem and for letting me know!
